th_repos:
    ip: '153.37.213.18'
    #ip dir
    port: '21'
    
    name: 'tyhoo.com/sdkftp'
    
    password: 'sdkftp.com'
    
    filter:
        '/th_repos/pyLibs':
            - '.py'
        '/th_repos/thLibs':
            - '.py'
        '/th_repos/cgtkLibs':
            - '.py'
        '/th_repos/maya/modules':
            - ''
        '/th_repos/maya/plug-ins':
            - ''
        '/th_repos/maya/scripts':
            - '.py'