thRepos:
    ip: '153.37.213.18'
    #ip dir
    port: '21'
    
    name: 'sdkftp'
    
    password: 'sdkftp.com'
    
    filter:
        pyLibs : 
            path: '/thRepos/pyLibs'
            excluded: 
                - 'history'
                - '.gitkeep'
                - '.gitignore'
            included:
                - ''
            info: "python第三方常用库" 
            
        maya-modules :
            path: '/thRepos/maya/modules'
            excluded:
                - 'history'
                - '.gitkeep'
                - '.gitignore'
                - 'shaveHaircut.mod'
                - 'MiarmyForMaya.mod'
                - 'pgYetiMaya.mod'
                - 'mtoa.mod'
            included:
                - ''
            info: "maya的插件环境配置"
            
        maya-Scripts :
            path: '/thRepos/maya/scripts'
            excluded:
                - 'history'
                - '.gitkeep'
                - '.gitignore'
                - '.py'
            included:
                - 'userSetup.py'
                - 'standaloneAbcWrite.py'
            info: "maya脚本"            
            
