th_repos:
    ip: '153.37.213.18'
    #ip dir
    port: '21'
    
    name: 'tyhoo.com/jarry'
    
    password: '19861230'
    
    filter:
        '/Support/th_repos/maya/plug-ins/mtoa_1.2.7.3_maya2015/bin':
            - '.py'
            - '.exe'
        '/Support/th_repos/pyLibs':
            - '.py'
        '/Support/th_repos/thLibs':
            - ''