th_repos:
    ip: '153.37.213.18'
    #ip dir
    port: '21'
    
    name: 'tyhoo.com/sdkftp'
    
    password: 'sdkftp.com'
    
    filter:
        pyLibs : 
            path: '/th_repos/pyLibs'
            excluded: 
                - '.py'
        thLibs :
            path: '/th_repos/thLibs'
            excluded:
                - '.py'
        cgtkLibs :
            path: '/th_repos/cgtkLibs'
            excluded:
                - '.py'
        modules :
            path: '/th_repos/maya/modules'
            excluded:
                - ''
        scripts :
            path: '/th_repos/maya/scripts'
            excluded:
                - '.py'
        mtoa_1.4.2.2_maya2016 :
            path: '/th_repos/maya/plug-ins/mtoa_1.4.2.2_maya2016'
            excluded:
                - ''
        Yeti2.1.6_Maya2016 :
            path: '/th_repos/maya/plug-ins/Yeti2.1.6_Maya2016'
            excluded:
                - ''
