th_repos:
    ip: '153.37.213.18'
    #ip dir
    port: '21'
    
    name: 'tyhoo.com/sdkftp'
    
    password: 'sdkftp.com'
    
    filter:
        '/th_repos/maya/plug-ins/mtoa_1.2.7.3_maya2015/bin':
            - '.py'
            - '.exe'
        '/th_repos/pyLibs':
            - '.py'
        '/th_repos/thLibs':
            - ''